#!/usr/bin/env ruby
#^syntax detection
  
forge "https://forgeapi.puppetlabs.com"
# mod 'puppetlabs/stdlib'

# mod 'ntp',
#   :git => 'git://github.com/puppetlabs/puppetlabs-ntp.git'

# mod 'apt',
#   :git => 'https://github.com/puppetlabs/puppetlabs-apt.git',
#   :ref => 'feature/master/dans_refactor'

mod 'puppetlabs/apt'
mod 'rtyler/jenkins'


mod 'puppetlabs/stdlib'
mod 'puppetlabs/git'

mod 'puppetlabs/apache'
mod 'puppetlabs/mysql'
mod 'mayflower/php'
